<?php
$kie['engines'] = array(
 'google.' => array('Google', 'q'),
 'alltheweb' => array('AlltheWeb', array('q', 'query')),
 '.voila.' => array('voila', 'kw'),
 'yahoo.' => array('Yahoo', array('p', 'va', 'directory')),
 'altavista.' => array('Altavista', 'q'),
 'lycos.' => array('Lycos',array('q', 'MT', 'query')),
 '.nomade.' => array('Nomade',array('s', 'MT')),
 'francite.' => array('Francite', 'search'),
 '.excite.' => array('Excite', array('search', 'qkw', 'q', 'key')),
 '.msn.' => array('MSN', array('s', 'q')),
 'metacrawler.com' => array('MetaCrawler', array('q', 'general', 'qry')),
 'laposte.' => array('La Poste', 'KEYWORDS'),
 'looksmart.' => array('looksmart', 'key'),
 'abcsearch.com' => array('ABCSearch', 'terms'),
 'search.com' => array('Search.com', 'q'),
 '9online.fr' => array('9Online Recherche', 'query'),
 'ixquick.' => array('Ixquick', 'query'),
 'lop.com' => array('Lop.com', 's'),
 'gograph.' => array('Gograph', 'mot_cle'),
 'northernlight.com' => array('Northenlight', 'qr'),
 'sympatico.' => array('Sympatico', 'query'),
 'search1-2.free.fr' => array('Free', 'q'),
 '.aol.' => array('AOL', array('query', 'q')),
 'wanadoo.' => array('Wanadoo', 'kw'),
 'webcrawler.' => array('Webcrawler', array('searchText', 's', 'qkw')),
 'web.toile.com' => array('La toile du québec', 'q'),
 'killou.' => array('Killou', 'mot'),
 'recherche.club-internet.' => array('ClubInternet', 'q'),
 '.multimania.' => array('Multimania', 'query'),
 '.dmoz.org' => array('DMOZ', array('query', 'search')),
 'hotbot.com' => array('HotBot', 'query')
);
?>
